import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    albumBackground: {
        alignSelf: 'flex-start',
        alignItems: 'center',
        backgroundColor: "#373737",
        borderRadius: 15,
        marginHorizontal: 10,
        overflow: "hidden",
        padding: 15,
        paddingBottom: 30,
    },
    albumContainer: {
        alignItems: 'center',
        alignSelf: 'center',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        marginTop: 35,
    },
    albumImage: {
        alignSelf: 'center',
        borderRadius: 15,
        height: 150,
        marginBottom: 10,
        width: 150,
    },
    albumInfo: {
        alignSelf: 'flex-start',
        color: 'white',
        fontSize: 14,
        marginBottom: 3,
    },
    bulletpoint: {
        alignSelf: 'center',
        backgroundColor: 'white',
        borderRadius: 100,
        height: 4,
        marginHorizontal: 10,
        width: 4,
    },
    button: {
        alignItems: 'center',
        alignSelf: 'center',
        backgroundColor: '#FF9283',
        borderRadius: 100,
        height: 25,
        justifyContent: 'center',
        marginTop: 15,
        width: 85,
    },
    buttonTitle: {
        color: 'black',
        fontSize: 12,
        fontWeight: 'bold'
    },
    container: {
        alignItems: 'center',
        alignSelf: 'center',
        flex: 1,
    },
    headerContainer: {
        alignSelf: "center",
        flexDirection: "row",
        marginTop: 75,
    },
    infoContainer: {
        alignSelf: "flex-start",
    },
    profileImage: {
        borderRadius: 200 / 2,
        height: 175,
        marginLeft: 50,
        overflow: "hidden",
        width: 175,
    },
    statsContainer: {
        alignItems: "center",
        flexDirection: "row",
        marginTop: 20,
    },
    statsBox: {
        alignItems: "center",
        flexDirection: 'row',
        justifyContent: "center",
    },
    text: {
        color: 'white',
    },
    title: {
        alignSelf: 'center',
        color: 'white',
        fontSize: 48,
        fontWeight: 'bold',
        marginTop: 30,
    },
    topSBackground: {
        alignSelf: 'stretch',
        alignItems: 'center',
        backgroundColor: '#373737',
        borderRadius: 15,
        flex: 1,
        margin: 10,
        padding: 10,
    },
    topSData: {
        alignSelf: 'flex-start',
        fontSize: 14,
        justifyContent: 'center',
        lineHeight: 22,
        marginBottom: 5,
        width: 220,
    },
    topSContainer: {
        alignItems: 'stretch',
        alignSelf: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 25,
        width: 600,
    },
});
