import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    albumContainer: {
        borderRadius: 20,
        flexDirection: 'column',
        margin: 3,
        paddingBottom: 15,
    },
    albumsContainer: {
        backgroundColor: '#222222',
        borderRadius: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        margin: 20,
        marginBottom: 0,
        padding: 10,
    },
    albumImage: {
        alignSelf: 'center',
        backgroundColor: '#FF9382',
        borderRadius: 10,
        height: 100,
        margin: 5,
        marginBottom: 5,
        width: 100,
    },
    albumInfo: {
        alignSelf: 'flex-start',
        color: 'white',
        fontSize: 12,
        marginStart: 5,
        width: 100,
    },
    backgroundCard: {
        alignSelf: 'center',
        backgroundColor: '#2D2D2D',
        borderRadius: 20,
        justifyContent: 'center',
        overflow: 'visible',
        width: '50%',
        height: 125,
    },
    bulletpoint: {
        backgroundColor: 'white',
        borderRadius: 100,
        height: 4,
        marginBottom: 3,
        marginHorizontal: 7,
        width: 4,
    },
    button: {
        backgroundColor: '#222222',
        borderRadius: 100,
        height: 125,
        justifyContent: 'center',
        marginHorizontal: 40,
        width: 125,
    },
    buttonIcon: {
        alignSelf: 'center',
        height: 100,
        width: 100,
    },
    buttonsContainer: {
        alignSelf: 'center',
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 20,
        marginBottom: 10,
    },
    cardContainer: {
        alignSelf: 'center',
        backgroundColor: '#373737',
        borderRadius: 20,
        marginBottom: 20,
        paddingBottom: 20,
        width: 450,
    },
    cardHeader: {
        alignSelf: 'flex-start',
        flexDirection: 'row',
        justifyContents: 'center',
        margin: 20,
        marginBottom: 0,
        width: '100%',
    },
    compText: {
        alignSelf: 'center',
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    container: {
        alignItems: 'center',
        flex: 1,
        marginBottom: 15,
    },
    logo: {
        alignSelf: 'center',
        borderRadius: 100,
        height: 75,
        width: 75,
    },
    nameText: {
        alignSelf: 'center',
        color: 'white',
        fontSize: 32,
        fontWeight: 'bold',
        marginStart: 5,
        marginLeft: 10,
        width: '75%',
    },
    nowPlayingContainer: {
        alignSelf: 'flex-start',
        backgroundColor: '#373737',
        borderRadius: 100,
        flexDirection: 'row',
        height: 40,
        justifyContent: 'center',
        marginBottom: 15,
        marginStart: 40,
    },
    nowPlayingImage: {
        alignSelf: 'center',
        borderRadius: 100,
        height: 30,
        marginStart: 10,
        resizeMode: 'center',
        width: 30,
    },
    nowPlayingText: {
        alignSelf: 'flex-start',
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
        marginStart: 40,
        marginBottom: 5,
    },
    profileImage: {
        alignSelf: 'center',
        backgroundColor: '#222222',
        borderRadius: 100,
        height: 50,
        resizeMode: 'contain',
        width: 50,
    },
    title: {
        alignSelf: 'flex-start',
        color: 'white',
        fontSize: 48,
        fontWeight: 'bold',
    },
    titleContainer: {
        alignSelf: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        margin: 30,
        marginBottom: 15,
    },
    text: {
        alignSelf: 'center',
        color: 'white',
        fontSize: 14,
        marginHorizontal: 10,
    },
    topSBackground: {
        alignItems: 'flex-start',
        backgroundColor: '#222222',
        borderRadius: 15,
        flex: 1,
        margin: 5,
        overflow: 'hidden',
        padding: 10,
    },
    topSContainer: {
        alignSelf: 'stretch',
        flexDirection: 'row',
        justifyContent: 'space-between',
        margin: 15,
    },
    topSData: {
        color: 'white',
        flex: 1,
        fontSize: 12,
        marginBottom: 5,
    },
})